[build]
  publish = "."
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["nodemailer"]

[functions.linzApi]
  timeout = 26

[functions.submitQuote]
  timeout = 15

[functions.sendNotification]
  timeout = 15

[functions.supabaseUpload]
  timeout = 20
